title: Mert Akhan Boran
author: MertAkhn06
description:
theme: minima
markdown: kramdown


# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Projects"
    url: /projects

author:
  name: Mert Akhan Boran
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/MertAkhn06"
