title: Mert Akhan Boran
author: MertAkhn06
description:
theme: minima
markdown: kramdown


# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Projects"
    url: /projects
